apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2020-01-30T17:19:24Z"
    labels:
      app: quotesapi
    name: quotesapi
    namespace: wadebee-quotes-dev
    resourceVersion: "52090503"
    selfLink: /apis/build.openshift.io/v1/namespaces/wadebee-quotes-dev/buildconfigs/quotesapi
    uid: a981ac08-4384-11ea-b7e0-0a580a82003e
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: quotesapi:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: quotes
      git:
        uri: https://github.com/wadebee/DO288-apps
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.2
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: xjq0sKEF_TIq-EzqnhTf
      type: GitHub
    - generic:
        secret: QB7VlN5decmG0ca5nw5D
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/php@sha256:d691584cc4879bf03db936666ae267e482ee9af083a4f94122c172ad82790b8d
      type: ImageChange
  status:
    lastVersion: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
